# ===============================================
#   SAPIs Configuration
# ===============================================
basePath=/api/

sapi.responseTimeout=120000
sapi.clientId=6137c4a5ac66468cb8b36ef47ca4a2f3

retail-sfcc-sapi.host=dev-retail-sfcc-sapi-5jec8b.5sc6y6-1.usa-e2.cloudhub.io
retail-comm-sapi.host=dev-retail-comm-sapi-5jec8b.5sc6y6-3.usa-e2.cloudhub.io
retail-oracle-wms-sapi.host=dev-retail-oracle-wms-sapi-5jec8b.5sc6y6-1.usa-e2.cloudhub.io

# ===============================================
#   CRON Configuration
# ===============================================
scheduler.cron=0 0 4 * * ?
scheduler.timezone=Asia/Kolkata

# ===============================================
#   Email Configuration
# ===============================================
#use comma separated values
mail.error.to=upendra.thunuguntla@gmail.com

# ===============================================
#   Misc Configuration
# ===============================================
retries.count=2
retries.gap=10000

# ===============================================
#   ObjectStore Configuration
# ===============================================
os.maxEntries=7500
os.ttl=10
os.expiration=30

# ===============================================
#   Batch Configuration
# ===============================================
batch.agg.size=40000
batch.blockSize=200000

# ===============================================
#   Local SFTP Configuration
# ===============================================
sftp.wd=D://SFTP
sftp.path=D://SFTP/retail/inbound
sftp.archive.path=D://SFTP/retail/inbound/archive
sftp.error.path=D://SFTP/retail/inbound/errors
sftp.outbound.path=D://SFTP/retail/outbound