# ===============================================
#   SAPIs Configuration
# ===============================================
sapi.clientSecret=![Gn1vxYvuIwZpfjg5bZ0aU4eBxwiW1V0qx6yqQRzIluZk890h3breYNbJku1pLa1a]